BogdanBargaoanu/MoneyStream

- server/app.js
- server/bin/www
- server/package-lock.json
- server/package.json
- server/public/stylesheets/style.css
- server/routes/index.js
- server/routes/users.js
- server/views/error.jade
- server/views/index.jade
- server/views/layout.jade
> Initial server setup

- server/app.js
- server/package-lock.json
- server/package.json
- server/routes/partners.js
- server/views/error.jade
This pull request includes several changes to add a new `partners` feature, update dependencies, and remove an unused view file. The most important changes include adding a new `partners` router, updating the `package-lock.json` and `package.json` files to include new dependencies, and modifying the `server/app.js` to use the new `partners` router.
* Added a new `partners` router with endpoints for getting a list of partners, getting a partner by username, adding a partner, and logging in a partner. (`server/routes/partners.js`)
* Implementation of API endpoints for partners.
* Password encryption and `db` checks.
* Updated `package-lock.json` and `package.json` to include the `jsonwebtoken` package and its dependencies. (`server/package-lock.json`, `server/package.json`) …
> Partner API implementation

- .gitignore
- exchange-admin/package-lock.json
- exchange-admin/package.json
- exchange-admin/src/Components/Dashboard/Navbar.css
- exchange-admin/src/Components/Partners/Partners.css
- exchange-admin/src/Components/Partners/Partners.jsx
This pull request includes several updates to the `exchange-admin` project, primarily focusing on adding a new table component to the Partners page and updating dependencies. The most important changes include adding the `react-table` dependency, implementing a new table component for displaying partner data, and updating CSS for the new table layout.
* Added `react-table` version 7.8.0 to `package.json` and `package-lock.json`. [[1]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931R22) [[2]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931R13371-R13382) [[3]](diffhunk://#diff-2cd7f2694b6b0befd44ffacfc90bfcba72a4db99706866ea8e09dba0862661f9R17)
* Updated `Partners.jsx` to fetch partner data from an API, use `react-table` …
> Partners page implementation

- exchange-admin/src/App.css
- exchange-admin/src/Components/Dashboard/Navbar.jsx
- exchange-admin/src/Components/Partners/Partners.css
This pull request includes changes to add a logout button with associated styles and functionality, as well as some minor cleanup in the CSS files. The most important changes include adding the logout button in the `Navbar` component, defining its styles, and implementing the logout functionality.
Logout button implementation:
* [`exchange-admin/src/Components/Dashboard/Navbar.jsx`](diffhunk://#diff-1b6ad48e1b1e067429deb8b5b8b8c3a35926073518a2e5b85b5bd608ae82dd8eR14-R18): Added a `logout` function to remove the user token from local storage and redirect to the login page. Added a logout button to the navigation bar that triggers this function. [[1]](diffhunk://#diff-1b6ad48e1b1e067429deb8b5b8b8c3a35926073518a2e5b85b5bd608ae82dd8eR14-R18) …
> Implemented logout button.

- exchange-admin/src/Components/Currency/Currency.css
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Partners/Partners.css
- exchange-admin/src/Components/Partners/Partners.jsx
- server/app.js
- server/routes/currency.js
This pull request includes significant updates to the currency management feature in the exchange admin panel. The changes introduce a new currency table with a corresponding API endpoint and enhance the UI for better user experience.
* [`exchange-admin/src/Components/Currency/Currency.css`](diffhunk://#diff-ae817c02efa300341242cc61f805dfdddc891e2552ee001e01d95d03c98fdf2cR1-R66): Added styles for the currency table, including positioning, scrollbar customization, and hover effects.
* [`exchange-admin/src/Components/Partners/Partners.css`](diffhunk://#diff-46973fec74108b839572ff5c4c4478ff5b46e1cda98cd630c350fba210fe11aaR52-R66): Added custom scrollbar styles for the partners table to match the currency table's design.
* [`exchange-admin/src/Components/Currency/Currency.jsx`](diffhunk://#dif …
> Implemented basic methods for currencies

- exchange-admin/src/App.css
- exchange-admin/src/App.js
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Dashboard/NavbarData.jsx
- exchange-admin/src/Components/Partners/Partners.css
- exchange-admin/src/Components/Partners/Partners.jsx
- exchange-admin/src/Components/Rates/Rates.jsx
- server/routes/currency.js
This pull request introduces several updates to the `exchange-admin` application, including the addition of a new `Rates` component, enhancements to the `Currency` and `Partners` components, and the implementation of JWT authorization in the `currency` API routes. The most important changes are summarized below:
* [`exchange-admin/src/Components/Rates/Rates.jsx`](diffhunk://#diff-7b9dde123bfad01281606c7a2a52d77923ae191db930b1a6c9d346f14d7cafc7R1-R17): Added a new `Rates` component with a basic structure and styling.
* [`exchange-admin/src/Components/Dashboard/NavbarData.jsx`](diffhunk://#diff-1476eaecde5d6d90e0dd2f807366228b5cb4af193ae3bc4c73a2ffb881ad4ccfR29-R34): Added a new navigation item for the `Rates` component.
* [`exchange-admin/src/Components/Currency/Currency.jsx`](diffhunk://#d …
> Searchable tables, adding/editing currency

- exchange-admin/src/App.js
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Login/LoginPage.jsx
- exchange-admin/src/Context/Toast/ToastContext.jsx
This pull request introduces a centralized toast notification system to improve user feedback across the application. The main changes include the creation of a `ToastContext` for managing toast messages and the integration of this context into various components.
* **Context Creation:**
* [`exchange-admin/src/Context/Toast/ToastContext.jsx`](diffhunk://#diff-f52dac5090b6da3c6a8a8fb8e7936411b523ff0576cdf03da3b9d8a26bd27838R1-R31): Created `ToastContext` with `ToastProvider` and `useToast` hook for managing toast notifications.
* **Integration in App Component:**
* [`exchange-admin/src/App.js`](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9R12-R17): Wrapped the application in `ToastProvider` to provide toast context to all components. …
> Toast context, touch-ups on currencies

- exchange-admin/src/App.css
- exchange-admin/src/Components/Currency/Currency.css
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Partners/Partners.css
- exchange-admin/src/Components/Partners/Partners.jsx
This pull request includes several changes to the CSS and JSX files in the `exchange-admin` project, focusing on animation adjustments, element styling, and class name consistency. The most important changes are summarized below:
* Modified the animation duration for the `slide-up-fade-in` effect to 0.5s in various elements for a quicker animation. (`exchange-admin/src/App.css`, `exchange-admin/src/Components/Currency/Currency.css`) [[1]](diffhunk://#diff-a93fd1ed4acb19176ab434a520d13951fa376ebe1ebe1f40629430cc38418882L89-R90) [[2]](diffhunk://#diff-a93fd1ed4acb19176ab434a520d13951fa376ebe1ebe1f40629430cc38418882R117-R118) [[3]](diffhunk://#diff-ae817c02efa300341242cc61f805dfdddc891e2552ee001e01d95d03c98fdf2cR61-R65)
* Added a new `.search-box` class with flex display and center …
> Animations

- server/app.js
- server/routes/currency.js
- server/routes/location.js
- server/routes/locations.js
This pull request includes updates to the `server` application, focusing on adding a new route and enhancing security for the currency routes. The most important changes are summarized below:
* Added `locationsRouter` to handle location-related requests in `server/app.js` [[1]](diffhunk://#diff-65890f102baa526da3cc5d65e0528ea728fa9fa63659a7f2e1d523686240359cR12) [[2]](diffhunk://#diff-65890f102baa526da3cc5d65e0528ea728fa9fa63659a7f2e1d523686240359cR175).
* Added Bearer token authentication to the currency routes in `server/routes/currency.js` to enhance security [[1]](diffhunk://#diff-cdf4ba7780721087e3b3e26a55471674e3057f0562a131afd1682fe2f1a8ef32R12-R13) [[2]](diffhunk://#diff-cdf4ba7780721087e3b3e26a55471674e3057f0562a131afd1682fe2f1a8ef32R81-R82) …
> Location API configuration

- exchange-admin/src/App.css
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Locations/Locations.css
- exchange-admin/src/Components/Locations/Locations.jsx
- server/routes/location.js
This pull request includes several changes to the `exchange-admin` project, focusing on enhancing the locations feature, improving error handling, and updating styles. The most significant updates include the addition of location management functionalities, improved error handling for authorization, and style adjustments.
* Added new functionalities to fetch, insert, update, and delete locations in `Locations.jsx`. This includes handling authorization headers and error responses.
* Updated the backend route to fetch locations for a specific partner, changing the endpoint from `/location/{idPartner}` to `/location/partner` and including additional fields in the response. [[1]](diffhunk://#diff-09072414dc51fea93a719f47050902f551d36265c79b02580d4ccd9a3b04bf37L86-L98) …
> Implemented locations

- exchange-admin/src/App.js
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Dashboard/Dashboard.jsx
- exchange-admin/src/Components/Locations/Locations.jsx
- exchange-admin/src/Components/Partners/Partners.jsx
- exchange-admin/src/Components/Rates/Rates.jsx
This pull request refactors the `exchange-admin` project to centralize the `Navbar` component usage and remove redundant imports. The main changes include the creation of an `AppContent` component to conditionally render the `Navbar` and the removal of `Navbar` imports from individual component files.
Centralized `Navbar` component usage:
* [`exchange-admin/src/App.js`](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9R13-R32): Added `AppContent` component to conditionally render `Navbar` based on the current path. [[1]](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9R13-R32) [[2]](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9L28-R42)
Removed redundant `Navbar` imports:
* …
> Navbar wrapper to app

- exchange-admin/src/App.js
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Dashboard/Dashboard.jsx
- exchange-admin/src/Components/Locations/Locations.jsx
- exchange-admin/src/Components/Partners/Partners.jsx
- exchange-admin/src/Components/Rates/Rates.jsx
This pull request includes changes to the `exchange-admin` project, focusing on the removal of redundant logo imports and the addition of toast messages for better user feedback. The most important changes are grouped by theme below:
* Removed `logo` import from `exchange-admin/src/Components/Currency/Currency.jsx`.
* Removed `logo` import from `exchange-admin/src/Components/Dashboard/Dashboard.jsx`.
* Removed `logo` import from `exchange-admin/src/Components/Locations/Locations.jsx`.
* Removed `logo` import from `exchange-admin/src/Components/Partners/Partners.jsx`.
* Removed `logo` import from `exchange-admin/src/Components/Rates/Rates.jsx`.
* Added toast message for successful currency deletion in `exchange-admin/src/Components/Currency/Currency.jsx`.
* Added toast message for …
> Centralised logo, success toast messages

- exchange-admin/src/App.css
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Locations/Locations.css
- exchange-admin/src/Components/Locations/Locations.jsx
- exchange-admin/src/Components/Partners/Partners.jsx
- exchange-admin/src/Components/Rates/Rates.css
- exchange-admin/src/Components/Rates/Rates.jsx
- exchange-admin/src/Context/Toast/ToastContext.jsx
The achievement of this pull request is the implementation of the `rates` in the `exchange-admin` project.
This pull request also includes several changes to the `exchange-admin` project, focusing on the `Currency` and `Locations` components, as well as some CSS updates. The changes aim to improve form validation, error handling, and user feedback through toast messages.
* Frontend implementation of the `rates`, with `insert`, `update`, `delete` functionalities.
* [`exchange-admin/src/Components/Currency/Currency.jsx`](diffhunk://#diff-04f031c772ec9ed91770617a67fc3718e45d8d9da0cc2da0599ba3a6a4b8abcaR32): Added toast messages for various error scenarios, such as failing to fetch, insert, update, or delete currencies. [[1]](diffhunk://#diff-04f031c772ec9ed91770617a67fc3718e45d8d9da0cc2da0599 …
> Rates implementation, various fixes

- exchange-admin/package-lock.json
- exchange-admin/package.json
- exchange-admin/src/App.css
- exchange-admin/src/Components/Dashboard/Dashboard.css
- exchange-admin/src/Components/Dashboard/Dashboard.jsx
- exchange-admin/src/Components/Partners/Partners.jsx
This pull request includes several updates to the `exchange-admin` project, focusing on integrating `react-google-charts` for data visualization, enhancing the Dashboard component, and making minor adjustments to CSS and API endpoints.
* Added `react-google-charts` dependency to `exchange-admin/package.json` and `exchange-admin/package-lock.json`. [[1]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931R19) [[2]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931R13244-R13252) [[3]](diffhunk://#diff-2cd7f2694b6b0befd44ffacfc90bfcba72a4db99706866ea8e09dba0862661f9R14)
* Updated `Dashboard.jsx` to include hooks for state management, data fetching with `axios`, and data preparation for charts. Integrated `react-google-charts` to …
> Google chart implementation to dashboard

- exchange-admin/src/Components/Dashboard/Dashboard.jsx
- exchange-client/package-lock.json
- exchange-client/package.json
- exchange-client/public/index.html
- exchange-client/src/App.css
- exchange-client/src/Components/AllRates/AllRates.css
- exchange-client/src/Components/AllRates/AllRates.jsx
- exchange-client/src/Components/BestRates/BestRates.css
- exchange-client/src/Components/BestRates/BestRates.jsx
- exchange-client/src/Components/Home/Home.css
- exchange-client/src/Components/Home/Home.jsx
- exchange-client/src/Components/NearestRates/NearestRates.css
- exchange-client/src/Components/NearestRates/NearestRates.jsx
- server/routes/rate.js
This pull request includes several changes across different parts of the project, focusing on enhancing the dashboard functionality, updating dependencies, and improving the user interface. Below are the most important changes:
* Added a new `useEffect` hook to update chart data whenever `rates` change, ensuring the chart reflects the latest data (`exchange-admin/src/Components/Dashboard/Dashboard.jsx`).
* Removed redundant code that previously updated chart data within the `fetchRates` function (`exchange-admin/src/Components/Dashboard/Dashboard.jsx`).
* Added `axios` to `exchange-client/package.json` and updated `package-lock.json` to include the new dependency (`exchange-client/package.json`, `exchange-client/package-lock.json`). …
> Nearest rates fetching with pagination

- server/routes/rate.js
This pull request includes the addition of a new endpoint to the `server/routes/rate.js` file. The new endpoint provides a list of rates for public use and includes detailed OpenAPI documentation.
* Added a new route `'/allRates'` to fetch a list of rates, including details such as `idRates`, `idLocation`, `address`, `idCurrency`, `name`, `date`, and `value`. The endpoint returns a JSON response with the rate details or an error message in case of a failure.
* Added OpenAPI documentation for the new `'/allRates'` endpoint, specifying the endpoint's description, tags, response formats, and possible status codes (200 for success and 500 for internal server error).… client use.
> API Endpoint for fetching all rates (client use)

- exchange-client/src/App.css
- exchange-client/src/Components/AllRates/AllRates.jsx
- exchange-client/src/Components/NearestRates/NearestRates.css
- exchange-client/src/Components/NearestRates/NearestRates.jsx
This pull request includes changes to the `exchange-client` project, focusing on enhancing the `AllRates` component and improving the CSS styles. The most important changes include fetching and displaying all rates, grouping rates by address, and updating the CSS styles for consistency.
Enhancements to `AllRates` component:
* [`exchange-client/src/Components/AllRates/AllRates.jsx`](diffhunk://#diff-faf27231513e2e3342751be60309b7663cc6fefeaba6c6812ee30e6629fb041eL1-R61): Added state management for `allRates` and `groupedRates`, implemented `useEffect` to fetch rates from the server, and grouped rates by address. Additionally, functions to generate map URLs from addresses and coordinates were added. [[1]](diffhunk://#diff-faf27231513e2e3342751be60309b7663cc6fefeaba6c6812ee30e6629fb041eL1-R61 …
> Implemented AllRates page

- exchange-client/src/Components/BestRates/BestRates.jsx
- server/routes/rate.js
This pull request introduces significant changes to the `BestRates` component and the server-side rate fetching logic. The main updates include adding new functionalities to fetch and display the best rates, grouping rates by address, and updating the server routes to support paginated fetching of the best rates.
* `exchange-client/src/Components/BestRates/BestRates.jsx`: 
- Introduced `useEffect`, `useState`, and `useCallback` to manage state and side effects for fetching and displaying best rates.
- Added new state variables `nearestRates`, `groupedRates`, and `currentPage` to manage the fetched data and pagination.
- Implemented `fetchBestRates` function to fetch rates from the server and update the state.
- Grouped fetched rates by address and displayed them in a structured format …
> Best rates client page

- exchange-admin/src/App.js
- exchange-admin/src/Components/Navbar/NavbarData.jsx
- exchange-admin/src/Components/Transactions/Transactions.jsx
- server/app.js
- server/routes/transaction.js
This pull request introduces several new features and improvements to the `exchange-admin` application and its associated server. The most significant changes include the addition of a new `Transactions` component, updates to the navigation bar to include transactions, and modifications to the server to support transactions.
* [`exchange-admin/src/App.js`](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9R9): Added import for `Transactions` component and a new route for `/transactions`. [[1]](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9R9) [[2]](diffhunk://#diff-c71bda62b500edde90818c765dbdf9bf62ca2e273f6dee0b135375ee1a0bf8f9R48)
* [`exchange-admin/src/Components/Navbar/NavbarData.jsx`](diffhunk://#diff-f3956b2a144f1c3e3a …
> Transactions skeleton

- exchange-admin/package-lock.json
- exchange-admin/package.json
- exchange-admin/src/App.js
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Dashboard/Dashboard.jsx
- exchange-admin/src/Components/Locations/Locations.jsx
- exchange-admin/src/Components/Login/LoginPage.jsx
- exchange-admin/src/Components/Navbar/Navbar.jsx
- exchange-admin/src/Components/Navbar/NavbarData.jsx
- exchange-admin/src/Components/Rates/Rates.jsx
- server/app.js
- server/routes/currency.js
- server/routes/location.js
- server/routes/partner.js
- server/routes/rate.js
- server/routes/transaction.js
This pull request includes several updates and improvements to the `exchange-admin` project, particularly focusing on dependency updates and enhancing the handling of navigation and error messages in various components.
* Updated `react-router-dom` from version `6.27.0` to `6.29.0` in `package-lock.json` and `package.json`. [[1]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931L21-R21) [[2]](diffhunk://#diff-2cd7f2694b6b0befd44ffacfc90bfcba72a4db99706866ea8e09dba0862661f9L16-R16)
* Updated `@remix-run/router` from version `1.20.0` to `1.22.0` in `package-lock.json`. [[1]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931L2966-R2968) [[2]](diffhunk://#diff-f8490331e427d9fb4569d680887a9e17b0f8cf15aebd71950a853da4a4603931L13280- …
> Token fix, useNavigate hooks and Transactions API

- exchange-admin/src/App.css
- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/DataTable/DataTable.jsx
- exchange-admin/src/Components/Locations/Locations.jsx
- exchange-admin/src/Components/Partners/Partners.jsx
- exchange-admin/src/Components/Rates/Rates.jsx
- exchange-admin/src/Components/Transactions/Transactions.css
- exchange-admin/src/Components/Transactions/Transactions.jsx
- exchange-client/src/Components/AllRates/AllRates.jsx
- exchange-client/src/Components/BestRates/BestRates.jsx
- exchange-client/src/Components/NearestRates/NearestRates.jsx
- server/routes/currency.js
- server/routes/location.js
- server/routes/rate.js
- server/routes/transaction.js
This pull request includes significant changes to the `exchange-admin` project, focusing on the refactoring of table components and the standardization of CSS classes. The most important changes include the creation of a new `DataTable` component, the replacement of individual table implementations with this new component, and the standardization of CSS class names across various files.
* [`exchange-admin/src/Components/DataTable/DataTable.jsx`](diffhunk://#diff-2e99bf6ad1051594f02273a611083e700bcaf238a50a6945ebf89a04fe9d20adR1-R51): Introduced a new `DataTable` component that uses `react-table` for rendering tables. This component centralizes the table logic and can be reused across different parts of the application.
* [`exchange-admin/src/Components/Currency/Currency.jsx`](diffhunk://#d …
> Implemented transactions

- exchange-client/package-lock.json
- exchange-client/src/Components/AllRates/AllRates.jsx
- exchange-client/src/Components/BestRates/BestRates.jsx
- exchange-client/src/Components/NearestRates/NearestRates.jsx
This pull request includes several changes to the `exchange-client` project, primarily focused on updating API URLs to use environment variables and modifying dependencies in the `package-lock.json` file. The most important changes are as follows:
* Updated API URLs in `AllRates.jsx` to use the `REACT_APP_API_URL` environment variable instead of hardcoded URLs.
* Updated API URLs in `BestRates.jsx` to use the `REACT_APP_API_URL` environment variable instead of hardcoded URLs. [[1]](diffhunk://#diff-f0704e90032cdcfbd6d4287e5dfdb008ac7bf4fbf7a9d1b8230ab420c6c1c80cR15-R19) [[2]](diffhunk://#diff-f0704e90032cdcfbd6d4287e5dfdb008ac7bf4fbf7a9d1b8230ab420c6c1c80cL38-R39)
* Updated API URLs in `NearestRates.jsx` to use the `REACT_APP_API_URL` environment variable instead of hardcoded URLs. …
> API URL with env for client

- exchange-admin/src/Components/Currency/Currency.jsx
- exchange-admin/src/Components/Dashboard/Dashboard.jsx
- exchange-admin/src/Components/Locations/Locations.jsx
- exchange-admin/src/Components/Login/LoginPage.jsx
- exchange-admin/src/Components/Partners/Partners.jsx
- exchange-admin/src/Components/Rates/Rates.jsx
- exchange-admin/src/Components/Transactions/Transactions.jsx
This pull request includes changes to multiple components in the `exchange-admin` project to replace hardcoded API URLs with dynamic URLs fetched from environment variables. This improves the flexibility and maintainability of the code, allowing for easier configuration changes.
* [`exchange-admin/src/Components/Currency/Currency.jsx`](diffhunk://#diff-04f031c772ec9ed91770617a67fc3718e45d8d9da0cc2da0599ba3a6a4b8abcaR18-R22): Updated API URLs in `fetchCurrencies`, `insertCurrency`, `updateCurrency`, and `deleteCurrency` functions to use `apiUrl` from environment variables. [[1]](diffhunk://#diff-04f031c772ec9ed91770617a67fc3718e45d8d9da0cc2da0599ba3a6a4b8abcaR18-R22) [[2]](diffhunk://#diff-04f031c772ec9ed91770617a67fc3718e45d8d9da0cc2da0599ba3a6a4b8abcaL77-R78) …
> API URL with env in admin app

- exchange-admin/src/Components/Transactions/Transactions.jsx
This pull request introduces changes to the `Transactions` component in the `exchange-admin` project, focusing on enhancing the user experience by integrating Google Maps functionality. The most important changes include adding new state properties, creating a function to generate Google Maps URLs, and embedding a map iframe within the component.
Enhancements to `Transactions` component:
* [`exchange-admin/src/Components/Transactions/Transactions.jsx`](diffhunk://#diff-15e1f48c36e5b04c5daf8a5c83ced736e2854f97ab4f22cf7712ed6070a947b8R21-R22): Added `start` and `finish` properties to the component's state to store the addresses for generating the map URL.
* [`exchange-admin/src/Components/Transactions/Transactions.jsx`](diffhunk://#diff-15e1f48c36e5b04c5daf8a5c83ced736e2854f97ab4f22cf7712ed6 …
> feat: add Google Maps integration to Transactions component for route visualization
